## Omnichannel Retail Sales and Inventory Analytics

In [2]:
# Import required libraries
import numpy as np 
import pandas as pd

In [3]:
# Load the dataset

raw_data = pd.read_csv('../1.data/retail_store_inventory.csv')
print(raw_data)

             Date Store ID Product ID Product Category Regions  \
0      01-01-2022     S001      P0001        Groceries   North
1      01-01-2022     S001      P0002             Toys   South
2      01-01-2022     S001      P0003             Toys    West
3      01-01-2022     S001      P0004             Toys   North
4      01-01-2022     S001      P0005      Electronics    East
...           ...      ...        ...              ...     ...
73095  01-01-2024     S005      P0016        Furniture    East
73096  01-01-2024     S005      P0017             Toys   North
73097  01-01-2024     S005      P0018         Clothing    West
73098  01-01-2024     S005      P0019             Toys    East
73099  01-01-2024     S005      P0020        Groceries    East

       Inventory Level  Units Sold  Units Ordered  Demand Forecast  Price  \
0                  231         127             55           135.47  33.50
1                  204         150             66           144.04  63.01
2                  102          65             51            74.02  27.99
3                  469          61            164            62.18  32.72
4                  166          14            135             9.26  73.64
...                ...         ...            ...              ...    ...
73095               96           8            127            18.46  73.73
73096              313          51            101            48.43  82.57
73097              278          36            151            39.65  11.11
73098              374         264             21           270.52  53.14
73099              117           6            165             2.33  78.39

       Discount Weather Condition  Holiday/Promotion  Competitor Pricing  \
0            20             Rainy                  0               29.69
1            20             Sunny                  0               66.16
2            10             Sunny                  1               31.32
3            10            Cloudy                  1               34.74
4             0             Sunny                  0               68.95
...         ...               ...                ...                 ...
73095        20             Snowy                  0               72.45
73096        10            Cloudy                  0               83.78
73097        10             Rainy                  0               10.91
73098        20             Rainy                  0               55.80
73099        20             Rainy                  1               79.52

      Seasonality
0          Autumn
1          Autumn
2          Summer
3          Autumn
4          Summer
...           ...
73095      Winter
73096      Autumn
73097      Winter
73098      Spring
73099      Spring

[73100 rows x 15 columns]

## Exploratory Data Analysis (EDA)

Before starting the data cleaning process, it is important to understand the dataset structure, column names, data types, missing values, duplicate records, and overall dataset information. This initial exploration helps identify data quality issues and prepares the dataset for further preprocessing and analysis.

In [4]:
# Display the 1st 5 rows of the dataset
raw_data.head(5)

,Date,Store ID,Product ID,Product Category,Regions,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,01-01-2022,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,01-01-2022,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,01-01-2022,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,01-01-2022,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,01-01-2022,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [5]:
# Display the last 5 rows of the dataset
raw_data.tail(5)

,Date,Store ID,Product ID,Product Category,Regions,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
73095,01-01-2024,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,01-01-2024,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,01-01-2024,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,01-01-2024,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,01-01-2024,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [6]:
# Display the shape of the dataset
raw_data.shape

(73100, 15)

In [7]:
raw_data.size

1096500

In [8]:
# Display the data types of each column and check for null values
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Product Category    73100 non-null  object
 4   Regions             73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [9]:
# Display the data types of each column
raw_data.dtypes

Date                   object
Store ID               object
Product ID             object
Product Category       object
Regions                object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition      object
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality            object
dtype: object

In [10]:
# Display the column names of the dataset
raw_data.columns

Index(['Date', 'Store ID', 'Product ID', 'Product Category', 'Regions',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='object')

In [11]:
# Display summary statistics of the dataset
raw_data.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [12]:
# Display the number of unique values for each column
raw_data.nunique()

Date                    731
Store ID                  5
Product ID               20
Product Category          5
Regions                   4
Inventory Level         451
Units Sold              498
Units Ordered           181
Demand Forecast       31608
Price                  8999
Discount                  5
Weather Condition         4
Holiday/Promotion         2
Competitor Pricing     9751
Seasonality               4
dtype: int64

#### The Date column was read as object. Since the dataset uses day-month-year format, it was converted to datetime using dayfirst=True.

In [13]:
raw_data['Date'].head()

0    01-01-2022
1    01-01-2022
2    01-01-2022
3    01-01-2022
4    01-01-2022
Name: Date, dtype: object

In [14]:
raw_data['Date'] = pd.to_datetime(raw_data['Date'], dayfirst=True)

In [15]:
raw_data['Date'].dtypes

dtype('<M8[ns]')

## Data Cleaning

### 1.Check null

In [17]:
raw_data.isnull()

,Date,Store ID,Product ID,Product Category,Regions,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73096,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73097,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73098,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73099,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
raw_data.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Product Category      0
Regions               0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [19]:
# Drop rows with missing values
raw_data.dropna(inplace=True)

### 2.Check duplicates

In [20]:
# Check for duplicate rows
raw_data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
73095    False
73096    False
73097    False
73098    False
73099    False
Length: 73100, dtype: bool

In [21]:
raw_data.duplicated().sum()

np.int64(0)

### 3. Remove duplicates

In [22]:
# Drop duplicate rows
raw_data.drop_duplicates(inplace=True)

### 4. Standardizing date/time formats

In [28]:
raw_data['Date'].head()

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Date, dtype: datetime64[ns]

### 5. Validating datatypes

In [29]:
raw_data.dtypes

Date                  datetime64[ns]
Store ID                      object
Product ID                    object
Product Category              object
Regions                       object
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Demand Forecast              float64
Price                        float64
Discount                       int64
Weather Condition             object
Holiday/Promotion              int64
Competitor Pricing           float64
Seasonality                   object
dtype: object